In [13]:
#Q4.2
#packages
import numpy as np

#random number generator
np.random.seed(123)

In [45]:
#creating the 3 random matrices
m1 = np.random.randint(-10, 11, (3,3))
m2 = np.random.randint(-10, 11, (3,3))
m3 = np.random.randint(-10, 11, (3,3))

print("M1:\n", m1)
print("Inverse of m1:")
print(np.linalg.inv(m1))
print("M2:\n", m2)
print("Inverse of m2:")
print(np.linalg.inv(m1))
print("M3:\n", m3)
print("Inverse of m3:")
print(np.linalg.inv(m1))

M1:
 [[-9 -3 -4]
 [-7 -9 -3]
 [ 8 -4 -5]]
Inverse of m1:
[[-0.06346154 -0.00192308  0.05192308]
 [ 0.11346154 -0.14807692 -0.00192308]
 [-0.19230769  0.11538462 -0.11538462]]
M2:
 [[-1 -2 -1]
 [-6 -2  8]
 [-6  2 -7]]
Inverse of m2:
[[-0.06346154 -0.00192308  0.05192308]
 [ 0.11346154 -0.14807692 -0.00192308]
 [-0.19230769  0.11538462 -0.11538462]]
M3:
 [[ 9  7 -3]
 [ 2 -2  4]
 [ 4  6  6]]
Inverse of m3:
[[-0.06346154 -0.00192308  0.05192308]
 [ 0.11346154 -0.14807692 -0.00192308]
 [-0.19230769  0.11538462 -0.11538462]]


In [36]:
#Q5
#packages
import pandas as pd

#loading dataset
df = pd.read_csv('kc_house_data.csv')

#dropping useless columns
df = df.drop(['id', 'date', 'zipcode'], axis=1, errors='ignore')

#features without price
features = [col for col in df.columns if col != 'price']

In [37]:
#part 1
#mean, minimum, maximum, variance
stats = pd.DataFrame({
    'mean': df[features].mean(),
    'min': df[features].min(),
    'max': df[features].max(),
    'variance': df[features].var()
})
print("Feature Stats:")
print(stats)

l_mean  = stats['mean'].idxmin(), stats['mean'].min()
h_mean = stats['mean'].idxmax(), stats['mean'].max()
l_var = stats['variance'].idxmin(), stats['variance'].min()
h_var = stats['variance'].idxmax(), stats['variance'].max()

print(f"Lowest average feature: {l_mean[0]} ({l_mean[1]})")
print(f"Highest average feature: {h_mean[0]} ({h_mean[1]})")
print(f"Lowest variance feature: {l_var[0]} ({l_var[1]})")
print(f"Highest variance feature: {h_var[0]} ({h_var[1]})")

Feature Stats:
                       mean        min           max      variance
bedrooms           3.370842     0.0000  3.300000e+01  8.650150e-01
bathrooms          2.114757     0.0000  8.000000e+00  5.931513e-01
sqft_living     2079.899736   290.0000  1.354000e+04  8.435337e+05
sqft_lot       15106.967566   520.0000  1.651359e+06  1.715659e+09
floors             1.494309     1.0000  3.500000e+00  2.915880e-01
waterfront         0.007542     0.0000  1.000000e+00  7.485226e-03
view               0.234303     0.0000  4.000000e+00  5.872426e-01
condition          3.409430     1.0000  5.000000e+00  4.234665e-01
grade              7.656873     1.0000  1.300000e+01  1.381703e+00
sqft_above      1788.390691   290.0000  9.410000e+03  6.857347e+05
sqft_basement    291.509045     0.0000  4.820000e+03  1.958727e+05
yr_built        1971.005136  1900.0000  2.015000e+03  8.627973e+02
yr_renovated      84.402258     0.0000  2.015000e+03  1.613462e+05
lat               47.560053    47.1559  4.77776

In [48]:
#part 2
feat_corr = df.corr(numeric_only=True)['price'].drop('price').sort_values(ascending=False)
print("Correlation with sorted price:")
print(feat_corr.to_frame(name='Correlation'))
print("Highest correlation feature:", feat_corr.idxmax(), f"({feat_corr.max()})")

Correlation with sorted price:
               Correlation
sqft_living       0.702035
grade             0.667434
sqft_above        0.605567
sqft_living15     0.585379
bathrooms         0.525138
view              0.397293
sqft_basement     0.323816
bedrooms          0.308350
lat               0.307003
waterfront        0.266369
floors            0.256794
yr_renovated      0.126434
sqft_lot          0.089661
sqft_lot15        0.082447
yr_built          0.054012
condition         0.036362
long              0.021626
Highest correlation feature: sqft_living (0.7020350546118003)


In [47]:
#part 3
print("As you can see, from all the correlation values, there seems to be no features with negative correlations to price in the dataset.")

As you can see, from all the correlation values, there seems to be no features with negative correlations to price in the dataset.
